Provice ChatGPT with the compile/run command
```
% cwhy converse --- g++ -std=c++14 tests/c++/modern-cpp-feature.cpp
tests/c++/modern-cpp-feature.cpp: In function ‘int main()’:
tests/c++/modern-cpp-feature.cpp:10:10: error: ‘erase_if’ is not a member of ‘std’; did you mean ‘enable_if’?
   10 |     std::erase_if(v, [](int i) { return i % 3 == 0 || i % 5 == 0; });
      |          ^~~~~~~~
      |          enable_if
==================================================
CWhy
==================================================
Calling: get_compile_or_run_command()
As expected, you're compiling your code with the flag `-std=c++14`, which means
that the compiler will follow the C++14 standard. However, `std::erase_if` is a
feature that was introduced in C++20.

To resolve this issue, update the compile command to use the C++20 standard by
replacing `-std=c++14` with `-std=c++20`, so your command should be `g++
-std=c++20 tests/c++/modern-cpp-feature.cpp`.

Please make sure that your GCC (GNU Compiler Collection) supports C++20. GCC 9
and later versions have support for most of the C++20 features.
==================================================
```